# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bshard.proto\x12\x06search\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"M\n\x13ScoredSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x18\n\x0cquery_vector\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\r\n\x05limit\x18\x03 \x01(\x05\"j\n\x03Hit\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05shard\x18\x04 \x01(\t\x12\x12\n\nbm25_score\x18\x05 \x01(\x02\x12\x16\n\x0esemantic_score\x18\x06 \x01(\x02\"+\n\x0eSearchResponse\x12\x19\n\x04hits\x18\x01 \x03(\x0b\x32\x0b.search.Hit2\x8c\x01\n\x0cShardService\x12\x37\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12\x43\n\x0cScoredSearch\x12\x1b.search.ScoredSearchRequest\x1a\x16.search.SearchResponseb\x06proto3')



_SEARCHREQUEST = DESCRIPTOR.message_types_by_name['SearchRequest']
_SCOREDSEARCHREQUEST = DESCRIPTOR.message_types_by_name['ScoredSearchRequest']
_HIT = DESCRIPTOR.message_types_by_name['Hit']
_SEARCHRESPONSE = DESCRIPTOR.message_types_by_name['SearchResponse']
SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'shard_pb2'
  # @@protoc_insertion_point(class_scope:search.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

ScoredSearchRequest = _reflection.GeneratedProtocolMessageType('ScoredSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCOREDSEARCHREQUEST,
  '__module__' : 'shard_pb2'
  # @@protoc_insertion_point(class_scope:search.ScoredSearchRequest)
  })
_sym_db.RegisterMessage(ScoredSearchRequest)

Hit = _reflection.GeneratedProtocolMessageType('Hit', (_message.Message,), {
  'DESCRIPTOR' : _HIT,
  '__module__' : 'shard_pb2'
  # @@protoc_insertion_point(class_scope:search.Hit)
  })
_sym_db.RegisterMessage(Hit)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'shard_pb2'
  # @@protoc_insertion_point(class_scope:search.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)

_SHARDSERVICE = DESCRIPTOR.services_by_name['ShardService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCOREDSEARCHREQUEST.fields_by_name['query_vector']._options = None
  _SCOREDSEARCHREQUEST.fields_by_name['query_vector']._serialized_options = b'\020\001'
  _SEARCHREQUEST._serialized_start=23
  _SEARCHREQUEST._serialized_end=68
  _SCOREDSEARCHREQUEST._serialized_start=70
  _SCOREDSEARCHREQUEST._serialized_end=147
  _HIT._serialized_start=149
  _HIT._serialized_end=255
  _SEARCHRESPONSE._serialized_start=257
  _SEARCHRESPONSE._serialized_end=300
  _SHARDSERVICE._serialized_start=303
  _SHARDSERVICE._serialized_end=443
# @@protoc_insertion_point(module_scope)
