FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy the entire python project
COPY . .
EXPOSE 8090
ENTRYPOINT ["python", "cmd/coordinator.py"]
